# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'PhotoBooth' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

  # Pods for PhotoBooth
  pod 'AFNetworking', '3.1.0'
  pod 'AWCameraView', '0.5.1'
  pod 'YCSlideShowImageView', '1.1.1'
  pod 'DLPhotoPicker', '1.0.3'
  pod 'Realm', '2.0.2'
  pod 'DRColorPicker', '1.0.11'
  pod 'MMPickerView', '0.0.1'


end
